- hosts: localhost
  collections:
    - oracle.oci

  tasks:
    - name: Install oci python SDK
      pip:
        name: oci
      register: result

    - debug:
        msg: "{{ result }}"

    - name: Get namespace name
      oci_object_storage_namespace_facts:
      register: result

    - debug:
        msg: "{{ result }}"
